version: '2'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    command: postgres -c 'max_connections=10000'
    ports:
    - "5431:5432"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
    - ./docker/mysql/test.cnf:/etc/mysql/conf.d/test.cnf
    ports:
    - "3307:3306"

  mongo:
    image: mongo:3
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
    - "27018:27017"
  redis:
    image: redis:alpine
    ports:
    - "6380:6379"
  test:
    build: ./