version: '2'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    command: postgres -c 'max_connections=10000'
    ports:
    - "5431:5432"

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
    volumes:
    - ./docker/mysql/test.cnf:/etc/mysql/conf.d/test.cnf
    ports:
    - "3307:3306"

  mongo:
    image: mongo:3
    environment:
      MONGO_INITDB_DATABASE: test
    ports:
    - "27018:27017"
  redis:
    image: redis:alpine
    ports:
    - "6380:6379"
  test:
    build: ./

#  influxdb:
#    image: influxdb:latest
#    environment:
#    - INFLUXDB_ADMIN_ENABLED=true
#    - ADMIN_USER="root"
#    - INFLUXDB_INIT_PWD="root"
#    - PRE_CREATE_DB="telegraf"
#    ports:
#    - "8083:8083"
#    - "8086:8086"
#    #env_file:
#    #  - 'env.influxdb'
#    volumes:
#    # Data persistency
#    # sudo mkdir -p /srv/docker/influxdb/data
#    - ./influxdb:/var/lib/influxdb


#  etcd:
#    container_name: etcd0
#    image: registry.cn-hangzhou.aliyuncs.com/coreos_etcd/etcd:v3
#    ports:
#    - "2379:2379"
#    - "4001:4001"
#    - "2380:2380"
#    environment:
#    - TZ=CST-8
#    - LANG=zh_CN.UTF-8
#    command:
#      /usr/local/bin/etcd
#      -name etcd0
#      -data-dir /etcd-data
#      -advertise-client-urls http://${host_ip}:2379,http://${host_ip}:4001
#      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
#      -initial-advertise-peer-urls http://${host_ip}:2380
#      -listen-peer-urls http://0.0.0.0:2380
#      -initial-cluster-token docker-etcd
#      -initial-cluster etcd0=http://${host_ip}:2380
#      -initial-cluster-state new
#    volumes:
#    - "/data/conf/etcd/data:/etcd-data"
    # - "/data/config/etcd/ca-certificates/:/etc/ssl/certs"